### ISSUE TITLE
Cookie Expiration date is saved as "End of Session" irrespective of the settings.

### ISSUE THREAD

**Issue by hchouhan** [ibericode/scroll-triggered-boxes#18]
STB cookie expiration data is saved as "End of Session", when when test mode is not enabled and more days have been set in the settings. 

http://www.tlu.ee/~jhnvaino/img/stb.png 

Tested this myself.

**Comment by lkraav** [comment]
@dannyvankooten this causes the popup to re-appear every time the person closes his browser, which could be due to crash or on purpose. Am I misunderstanding something here? Shouldn't the cookie persist across sessions?

**Comment by dannyvankooten** [comment]
@lkraav You are totally right, not sure how I missed this for so long. I just pushed out an update of the plugin which fixes this issue. Sorry for the delay!

**Comment by lkraav** [comment]
We implemented the EU cookie policy popup on STB. Because why not, right. It's funny how people living on the site every day for nearly two months after launch, never said anything about the e-mail capture box popping up too often. But cookie policy sure caught their eye :)

**Comment by lkraav** [comment]
@dannyvankooten I think we still have a problem with the STB code not auto-upgrading the cookie for existing customers? So if they already got the "Session"-length cookie from before, it is not going to respect the new expiry date until it's manually deleted.

Feels like the cookie should be erased first and then re-created. Thoughts?

**Comment by lkraav** [comment]
@dannyvankooten i see that v2.1.2 changelog seems to address my last comment here. If that's the case, tyvm sir. Could you confirm this for me?

**Comment by dannyvankooten** [comment]
Hi @lkraav,

I'm afraid I do not fully understand what's happening here, a cookie expiring at the end of a browser's session **will thus be deleted at the end of the session / when the browser closes**. Right? So it seems like manually deleting the cookie is not necessary, since it's deleted at the end of the session anyway.

Sorry I didn't get back to you before by the way - this one slipped through my attention. 

Let me know please.
